<?php

/**
 * @file
 * Contains wh_import_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\wh_import_vlb\VlbService;



/**
 * Implements hook_help().
 */
function wh_import_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wh_import_ui module.
    case 'help.page.wh_import_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WH Import User Interface') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function wh_import_ui_cron() {

  \Drupal::logger('wh_import_ui_cron')->notice("cron is running now");
  // Get queue.
  $queue = \Drupal::queue('vlb_queue');
  //get all books
  $import_service = \Drupal::service('wh_import_vlb.vlb');
  $eans = $import_service->getAllEans();
  $total = count($eans);
  //get log-prefix
  $config = \Drupal::config('system.site');
  $site_name = $config->get('name');
  $log_prefix = format_date(time(), 'custom', 'dmy_His');
  $i = 0;
  foreach ($eans as $ean) {
    $i++;
    // Create item to queue.
    $data = (object) ['ean' => $ean, 'count' => $i, 'total' => $total, 'log_prefix' => $log_prefix];
    $queue->createItem($data);
  }
  logImport($i.' eans to import', $log_prefix);
}
/**
 * Implements hook_cron().
 */
function wh_import_ui_mycron() {

  \Drupal::logger('wh_import_ui_cron')->notice("mycron is running now");
  // Get queue.
  $queue = \Drupal::queue('vlb_queue');
  //get all books
  $import_service = \Drupal::service('wh_import_vlb.vlb');
  $eans = $import_service->getAllEans();
  $total = count($eans);
  //get log-prefix
  $config = \Drupal::config('system.site');
  $site_name = $config->get('name');
  $log_prefix = format_date(time(), 'custom', 'dmy_His').'_'.$site_name;
  $i = 0;
  foreach ($eans as $ean) {
    $i++;
    // Create item to queue.
    $data = (object) ['ean' => $ean, 'count' => $i, 'total' => $total, 'log_prefix' => $log_prefix];
    $queue->createItem($data);
  }
  logImport($i.' eans to import', $log_prefix);
}

function logImport($message, $log_prefix){
  $log_path = \Drupal::service('file_system')->realpath('public://'.$log_prefix.'_vlb_import_ok.log');
  error_log($message . PHP_EOL, 3, $log_path);
}

/**  
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().  
 */  
function wh_import_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  dpm('test');
}
