<?php

/**
 * @file
 * Contains wh_import_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\wh_import_vlb\VlbService;



/**
 * Implements hook_help().
 */
function wh_import_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wh_import_ui module.
    case 'help.page.wh_import_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WH Import User Interface') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function wh_import_ui_cron() {

  \Drupal::logger('wh_import_ui_cron')->notice("wh_import_ui_cron is running now");
  // Get queue.
  $queue = \Drupal::queue('vlb_queue');
  //get all books
  $import_service = \Drupal::service('wh_import_vlb.vlb');
  $eans = $import_service->getAllEans();
  foreach ($eans as $ean) {
    // Create item to queue.
    $data = (object) ['ean' => $ean];
    $queue->createItem($data);
  }
  // Report on number of items present
  // $numbers = $queue->numberOfItems(); // Prints "1"
  // \Drupal::logger('wh_import_ui_cron')->notice("numberOfItems: ".$numbers);
  // while($item = $queue->claimItem()) {
  // // Delete the item from queue.
  //   \Drupal::logger('wh_import_ui_cron')->notice("item claimItem ");

  //     $queue->deleteItem($item);
  //     \Drupal::logger('wh_import_ui_cron')->notice("deleteItem: ");
  // }
}
